version: '3.8'

services:
  write-db:
    image: postgres:latest
    container_name: postgres_write_db
    environment:
      POSTGRES_DB: write_db # Name of the database to create
      POSTGRES_USER: postgres # Username for the database
      POSTGRES_PASSWORD: postgres # Password for the user
    ports:
      - 5432:5432 # Expose port 5432

  read-db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"
